version: '3.8'
services:
  service-a:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - app-network

  service-b:
    build:
      context: ../service-b
    ports:
      - "8080:8080"
    networks:
      - app-network

  service-c:
    build:
      context: ../service-c
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
